### ISSUE TITLE
Dockerize application

### ISSUE THREAD

**Issue by chris-dare** [dexios1/firelord#2]
Dockerize this app as seen in my [FastAPI scaffold](https://github.com/dexios1/fastapi-boilerplate).

**Comment by chris-dare** [comment]
Create ./Dockerfile
Contents:

```

# pull official base image
FROM python:3.8.3-slim-buster

# set working directory
WORKDIR /app/

# set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update \
    && apt-get -y install netcat gcc curl \
    && apt-get clean

# Install Poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./pyproject.toml ./poetry.lock* /app/

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV=true
RUN ls
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --no-dev ; fi"

# add app
COPY ./ /app
ENV PYTHONPATH=/app

**Comment by chris-dare** [comment]
Create ./docker-compose.yml
Contents:
```
version: "3.3"

services:
  web:
    build: ./
    command: uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      - VAR=${VAR?Variable not set}
```
